### ISSUE TITLE
Unify buildbot scripts

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#116]
Right now, buildbot has two scripts. After making buildbot take the platform as an argument, there's some duplicate functionality in `buildbot` and `prepare_cloud_image.py`.

Let's turn `prepare_cloud_image.py` into `buildbot download`.

**Comment by mgax** [comment]
Ok, but maybe call it something other than `download`, because it does so much more. It would produce a VM image that can be tarballed as an artifact and downloaded, much like a vagrant box. Actually https://github.com/liquidinvestigations/buildbot/pull/8 gets us closer to this goal.

So the flow would be:
* generate an image, `buildbot images provision` maybe? It would be nice to give it a custom provisioning script, e.g. to pre-install ansible and docker.
* export the image and additional files as tarball, so it can be saved as a build artifact - `buildbot images export`? This is analogous to `docker save`.
* show available images, `buildbot images ls`
* import the image from a file or URL: `buildbot images import URL|PATH`
* run a VM - `buildbot login [--image=liquid-x64]` and `buildbot run [--image=liquid-x64]` (`--image` is only required if you have multiple images imported.

Want to run a liquid nightly in buildbot? Take the nightly image, convert to qcow, add an `options.json`, tarball the two, and you have an image that can be imported by `buildbot images import`.
