### ISSUE TITLE
liquid website links to jenkins for images. no ARM images.

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#184]
ilquidinvestigations.org has an 'images' link. It seems to link to the last successful builds. Maybe it should link to some 'stable' archived builds instead? There's no ARM build here right now.

How to fix?

https://jenkins.liquiddemo.org/job/liquidinvestigations/job/setup/job/master/lastSuccessfulBuild/artifact/

**Comment by mgax** [comment]
There are two "images" links, one for x86_64 and one for arm64. The wording for the 2nd one is wrong because it mentions "arm32" which we don't build for.

We can point to "stable builds" once we have such an archive. I'd even insist on version numbers for them. Maybe the Q3 final images are a good candidate to start. Until then, jenkins for the master branch is all we have.
