### ISSUE TITLE
no collections available to search on demo server

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#198]

**Comment by mgax** [comment]
First we should require login on all apps (https://github.com/liquidinvestigations/liquidinvestigations/issues/215) then we can make the davros collection public by default.

**Comment by mgax** [comment]
Fixed by https://github.com/hoover/search/commit/d4a5a05b0a8c88e4d4482450e0cfc9758e0469bd and https://github.com/liquidinvestigations/setup/commit/92beb29894d29b627e63e884543c4823406ff0f5. @mrc-toader please test this in the next build - the `davros-sync` collection should be searchable without having to configure it from the django admin.

Since we don't require authentication to view hoover pages, this means `davros-sync` is truly public, but it will be fixed when we have proper SSO.

**Comment by mgax** [comment]
Works.
