### ISSUE TITLE
make 'first boot' wizard available for demo somewhere

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#201]
this also needs coverage in the 'facelift' effort by pinkfox.

**Comment by mgax** [comment]
> this also needs coverage in the 'facelift' effort by pinkfox.

This deserves a separate issue.

**Comment by gabriel-v** [comment]
> available for demo somewhere

This requires more work than it's worth. We can't open them on `liquiddemo.org` because that breaks the flow of deploying the demo server.

As we needed these pages for testing reference, have some screenshots

**Initial welcome screen**
![screenshot_20171204_171813](https://user-images.githubusercontent.com/7493327/33560273-f9c4af6c-d917-11e7-88ee-992f3d139730.png)

**Second welcome screen**
![screenshot_20171204_171900](https://user-images.githubusercontent.com/7493327/33560294-0a6000b0-d918-11e7-95a4-0d78e5e3022f.png)

**Login screen**
![screenshot_20171204_172051](https://user-images.githubusercontent.com/7493327/33560304-11b4cc9c-d918-11e7-87ac-dc531e6df393.png)
