### ISSUE TITLE
Bug report on Liquiddemo

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#275]
Included all issues & screenshots in this Bug report: https://docs.google.com/document/d/14cPETNr_Av4e5lv_qIb-byrwi5NIUbFhutWqaKIA8SI/edit

**Comment by mgax** [comment]
> When going to Davros, the  blue wrapper/navigation bar disappears.  - Bug?

* The menu bar was disabled because of performance issues, we'll bring it back: https://github.com/liquidinvestigations/liquidinvestigations/issues/258

> Upload document to Davros was fine
> Hitting the back button I was sent directly to Hoover. Easier to be sent back to the Dashboard page.

The back button depends on where you came from. If you came from hoover, it takes you back to hoover.

> Search on Hoover, brings up the newly uploaded document fairly fast. 
> Suggestion: Would be nice to have a UI notification for larger documents: ‘indexing in progress’

Yeah that would be nice to have. Let's leave it for later. No need for a separate issue, we'll surely notice this problem again.

> The Hoover search results view is screwy: big pie chart covers the results/page section - Bug

Covered by https://github.com/liquidinvestigations/liquidinvestigations/issues/263

> Annotation only works on the preview screen. Not on the original file and not if you open the doc in a new window - Bug? (see screenshot below)
> Hoover annotations don’t stick when performing a new search on the same search term. Looks like everything is being reset (clean slate). Bug

Covered by https://github.com/liquidinvestigations/setup/issues/67 - annotations should not appear on the search page, only on document pages.

> Dokuwiki annotations don’t stick either. Bug 

Created new issue: https://github.com/liquidinvestigations/liquidinvestigations/issues/277

> Suggestion: I like the fact that one can make Wiki annotations and Hoover annotations. Would be cool to use J.Udell script to programmatically send Hoover annotations into Wiki Pages.

That  requires a browser extension which needs to be configured with the hypothesis server's address. Needs more discussion.

> Matrix UI a bit clunky (see attached screenshot); icons need to be better arranged not to be overlapping - Bug

We should use Riot instead of the default matrix UI: https://github.com/liquidinvestigations/liquidinvestigations/issues/276
