### ISSUE TITLE
Demo server build scripts (from images)

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#39]
continuous deployment to demo server

- first manual deployment (qemu+libvirt)
- dns config - demo.liquidinvestigations.org
- https (letsencrypt)
- persistent volume that doesn't get nuked on deploy (https certs)
- manual trigger for redeploy

**Comment by dreamlayers** [comment]
We've already got hoover.liquidinvestigations.org, hypothesis and client.hypothesis, though all are pointed to the same IP as the web site. If that's not changed, reverse proxy can be used to send them to a different server.

There's also a "liuid_stage+test" VM at a different IP.  Is that doing something now?  I was thinking it could be used for this. Deploying from automated builds every night is a lot like testing and staging.

For a public demo it may be good to at least eventually only update after some testing is done.

**Comment by mgax** [comment]
> We've already got hoover.liquidinvestigations.org, hypothesis and client.hypothesis, though all are pointed to the same IP as the web site. If that's not changed, reverse proxy can be used to send them to a different server.

I think we should set up `demo.liquidinvestigations.org` and `*.demo...` DNS records, so the purpose of that domain is clear. We do need a wildcard DNS entry because each app in the liquid bundle lives in its own subdomain.



> For a public demo it may be good to at least eventually only update after some testing is done.

Yep, I agree, and it would be great to develop a smoke testing suite, to be run automatically after setup+buildbot. Not sure if we should prioritize this before the Q2 delivery though.

**Comment by dreamlayers** [comment]
> I think we should set up demo.liquidinvestigations.org and *.demo... DNS records, so the purpose of that domain is clear. We do need a wildcard DNS entry because each app in the liquid bundle lives in its own subdomain.

Sounds good and exists already. They point to the web server IP though, so they need changing or reverse proxy.

**Comment by dreamlayers** [comment]
My proposed plan now is:

* Don't bother with changing DNS. I don't know when that would be possible and it's not necessary.
* Use `demo.liquidinvestigations.org` and `*.demo...` . Change `liquid_domain` to that when building image. It makes more sense than liquid.example.com.
* Handle Let's Encrypt and https:// on the web server and use http:// reverse proxy forwarding to demo machine. Still secure when it's on the same machine.
* Demo machine can be on NAT; no need for a public IP
* Do an `apt dist-upgrade` from the build or at least install the security upgrades

**Comment by mgax** [comment]
> Don't bother with changing DNS. I don't know when that would be possible and it's not necessary.

It would make our lives much easier if we didn't have to reverse proxy the demo server through the web vm, so I think we should push to get the DNS change.

> Change liquid_domain to that when building image. It makes more sense than liquid.example.com.

Yes, definitely. The domain name should be set as part of the first-boot process, not as part of image building.

> Do an apt dist-upgrade from the build

Yes! We disabled dist-upgrade because it slowed down ansible when running in local development, but there should be a flag for this. Maybe in `ansible/vars/config.yml`.

Re. HTTPS - for the demo machine we can use letsencrypt with some way to persist the certificates across redeployments. We need this kind of functionality at some point when production users have their own HTTPS certs (perhaps they purchase a wildcard cert from a commercial CA). Let's talk about how to achieve this.

**Comment by dreamlayers** [comment]
Okay, so I have this working, but not committed yet and not set up automatically via cron.

One script, `/home/imgbuild/make_demo_image.sh` is meant to run under buildbot to prepare the image. I didn't commit it into setup because it is part of our private infrastructure. I could either put it into the private repository and copy it from there to shared of buildbot before running, or I could just commit it to setup anyways.

The other script `/usr/local/bin/make_demo_image.sh` simply kills the VM if it's running, and then moves the image into the right folder and starts the VM. The imgbuild user is specifically allowed to run that one script via sudo, and I believe that is safe because it is trivial.

I don't know how to make `update-grub` work correctly from the chroot, so if a kernel upgrade is installed inside the chroot it will mess up the grub configuration and make the image unbootable. So I'm instead upgrading packages at the end of rc.local, and then rebooting.

The vm name is `88.99.105.242_liquid_demo` and it uses serial console so you can `sudo virsh console 88.99.105.242_liquid_demo`.  Once it is up you can go to http://liquiddemo.org/ and play around. Though I'm not going to leave it up before others agree it should be up.

**Comment by mgax** [comment]
I don't think we should deploy a custom image for the demo. It should just use a regular image. This needs some first-boot functionality, e.g. to run a custom script from usb stick, which we plan to do this week anyway. So let's skip custom images altogether and do it with first-boot from the start.

**Comment by dreamlayers** [comment]
The 3 changes I'm doing so far, along with the reasoning:

* It must set up the network interface. The image wouldn't set it up by default, and it's useless without networking.

* It should upgrade packages (or at least do the security updates). This thing is going on the Internet and we should try to keep it safe.

* It's nice to be able to see the console via `virsh console`, so I switch it to a serial console for that.

**Comment by mgax** [comment]
> It must set up the network interface. The image wouldn't set it up by default, and it's useless without networking.

Howcome the network interface is not working? I would expect the VM to see an Ethernet interface and do DHCP on it, no?

> It should upgrade packages (or at least do the security updates). This thing is going on the Internet and we should try to keep it safe.

Absolutely. But look, the demo server is going to boot from an image, and it will not be always up to date. I think that, on first boot, it should do all updates, reboot if necessary, enable apt daily updates, and only afterwards it should start services and allow network traffic.

> It's nice to be able to see the console via virsh console, so I switch it to a serial console for that.

Can we make all our images use the serial port if it's available?

**Comment by dreamlayers** [comment]
> Howcome the network interface is not working? I would expect the VM to see an Ethernet interface and do DHCP on it, no?

Typically when a desktop Linux system does that, it's because it is running NetworkManager, which isn't installed. We can use systemd-networkd, which is probably a better choice for a server. The older /etc/network/interfaces mechanism works but is set up for specific interface names, and now Linux uses various different names, so you can't just set up eth0.

> Absolutely. But look, the demo server is going to boot from an image, and it will not be always up to date. I think that, on first boot, it should do all updates, reboot if necessary, enable apt daily updates, and only afterwards it should start services and allow network traffic.

Sounds good.

> Can we make all our images use the serial port if it's available?

Linux sets the console via a kernel command line parameter. If it's set to a non-existent serial port, boot can hang, like we were seeing in VirtualBox at first. So, I'm not sure how to auto-detect that. It wouldn't be hard to later run a getty on a serial port if it is available.

**Comment by alsegno** [comment]
The scope of this is not 'continuous deployment', but just some scripts that will do deployment in time for the demo this week.

Alex to provisionally take this task and ensure that we can deploy an image to the demo server. In addition Alex to handle DNS stuff for this and a 'landing page' that points people at our contact information.

**Comment by alsegno** [comment]
@mgax after our discussion yesterday, can we agree that the 'continuous deployment' scripts are out of scope for Q2, and that we will configure the demo server manually? That lets us remove the 'hard requirement' label, change the milestone, and bounce it back to backlog...

or am i reading things wrong?

**Comment by mgax** [comment]
> can we agree that the 'continuous deployment' scripts are out of scope for Q2, and that we will configure the demo server manually?

Yes. And it's not too bad, we can still use ansible to update the demo server.

**Comment by alsegno** [comment]
ok. i'll change the milestone, labels, and move to backlog. huzzah!

**Comment by alsegno** [comment]
As we didn't complete 'continuous deployment' for Q2, I'd like to see it done early in Q3. This doesn't have to be automatic nightly deployment, but should allow us to run a script that deploys a nightly x86 build of our choosing to the demo box.

Demo box config and data (hoover data/users) should be persisted when we do this. This may require some discussion.

I'd like to see this so that we don't take on the burden of manually maintaining the demo box with each update to the bundle.

**Comment by alsegno** [comment]
first step is to merge demo branch into master, then move into scripting the setup of a booted image for 'real world' use.

this will include https & other stuff.

**Comment by gabriel-v** [comment]
The setup `demo` branch pull request is here: https://github.com/liquidinvestigations/setup/pull/25.

After that is merged, we will need the internal infrastructure inventory to be finished, so we have a clear way to set up the demo VM with `virsh`, with a persistent disk that holds https certs & others.

**Comment by mgax** [comment]
I managed to boot the latest nightly in qemu, connect to the screen with vnc, and log in as the liquid user.

To enable qemu's VNC server, add this to the command line: `-display vnc=localhost:5`, then connect to localhost port 5905 with a vnc client.

The default SSH server is broken. There are no server private keys. Running `dpkg-reconfigure openssh-server` will generate them. Also, [this code](https://github.com/liquidinvestigations/setup/blob/master/ansible/roles/devel/tasks/main.yml#L24) replaces the wrong occurence of `PasswordAuthentication` in the sshd config, which ends up containing `PasswordAuthentication no`, and then `PasswordAuthentication yes` near the end, and the first line takes effect, thereby disallowing password authentication. Maybe it should be `regexp: "^[#]?PasswordAuthentication "`, I will experiment tomorrow.

The next step is to get SSH working and verify that the server listens on port 80 with all apps working.

**Comment by mgax** [comment]
Today I found @gabriel-v's notes about setting up the demo server. I'm hacking together a buildbot script (https://github.com/liquidinvestigations/setup/compare/demoserver) that takes a nightly image and turns it into a demo server image. So far it:

* creates a swapfile
* fixes sshd
* configures passwordless sudo for liquid
* configures the `ens3` network interface
* installs ansible and the `setup` repo, so it can change the domain name

Currently, ansible fails, because it's being run in chroot using `bin/install` and there's no dockerd. Maybe it should use the chroot ansible scripts. Stay tuned.

**Comment by mgax** [comment]
The PR https://github.com/liquidinvestigations/setup/pull/34 is merged. It does most of the setup for the demo server. It still needs https (https://github.com/liquidinvestigations/setup/issues/38) and some automation to get it into production.

**Comment by mgax** [comment]
Done; next step is https://github.com/liquidinvestigations/liquidinvestigations/issues/111.
