### ISSUE TITLE
OAuth support for Davros + dockerize

### ISSUE THREAD

**Issue by alsegno** [liquidinvestigations/liquidinvestigations#4]
Davros to support using arbitrary OAuth providers. This will support our 'single sign on' requirement for Q2.

**Comment by alsegno** [comment]
Per @nightsh this is progressing and we should have a first look today.

**Comment by nightsh** [comment]
Some updates on this, to have a written record.

> TL;DR: Fork Davros, figure out the easy way what we want from its behaviour, when the workflow is complete extract all our code into an Ember engine + a simple build strategy.

There are multiple ways of accomplishing this, each with its own implications. I have experimented with them all in the past few days:

* [Ember engines](http://ember-engines.com) – this is my fav so far, it mounts a specially crafted addon inside the app. It feels like a wrapper in terms of decoupling logic from the app, but it's not fully decoupled (you have to add a package in `package.json` and mount its routes in `router.js`). Everything can be done automatically using a small 2-3 lines build script.
* Ember addons – the classic approach, having a small addon that depends on `torii`, the OAuth wrapper for Ember. Downside is that I had to throw a lot of curve balls by using blueprints in order to achieve what we want here. Good part: it's the most common thing to do around Ember. Bad part: it's not routable.
* [Ember routable components](https://github.com/ef4/rfcs/blob/routeable-components/active/0000-routeable-components.md) – would be ideal, just I don't expect them to land into the framework anytime soon. It's still in RFC state, and it's quite an ambitious initiative: the plan is to eliminate the need for controllers and move a bit more into the web components world, but in a more advanced way. Sadly, not our cup of tea at the moment.
* Simple node app that requires `davros` via `package.json` and mounts it in, so basically a wrapper. Harder to do, as Davros is not built as a typical node package, but as a full blown app. That would mean a lot of tightly coupled `require` and `import` statements that are likely to break following Davros development cycle. Also high chance of `npm` not wanting to play ball due to some things that are awkward to import (having a separated instance of Ember running inside the wrapper, with a bit of shared context and some more JS scoping hell)
* fork Davros and hack it, while pulling all changes from upstream: high maintenance, easiest to get started with. I don't need to get into details with this approach.

---

Alright, so having these variants, what's the plan?

After trying out the above ideas, I realised we have some parts we never thought about. Or at least I didn't care enough by now. For example, what does it look like when you're not logged in? Are we going to support multiple providers? Multiple liquid-core nodes? Do we need to constantly (automatically) inject stuff into its env config? (tokens etc) Plus some other templates-related and routes-related questions.

So: I am now hacking on Davros to prototype the idea, taking special care not to pollute the code base – so working as decoupled as I can, with importable modules where needed, not touching its controllers and routes. When we're stable, I can gather everything into a OAuth engine, package it, publish it, then just add the thing to Davros requirements at build time (plus a pre-build one liner, I guess). That's a one day job.

Bonus: if I play the cards right, the end result should be reusable for other Ember apps as well.

**Comment by alsegno** [comment]
@nightsh what do you need from me/us *now* in terms of answers to the 'parts we never thought about'?

**Comment by nightsh** [comment]
Ah, nothing really, it's just the first time I encountered them. How does the authentication worfkflow integrates with Davros normal operations, adding providers, really tiny things that are only seen while getting your hands dirty 😅 
I only have one question so far: are we going for multiple providers in our scenario(s), or one liquid core node should rule over who gets to access Davros? I can add as many as we need to, but it has some implications for templating, env configuration and maybe the blueprints, if I get to use such things.

For all the others, given it's pretty straightforward, I don't need any input beforehand.

**Comment by nightsh** [comment]
Ah btw, I have a Davros that logs in via facebook, now I'm brushing up the view layer. I just installed/configured a core server locally and I'll be attempting a login shortly. Fingers crossed!

_Also, PR might be coming through for core documentation. But that's another story._

**Comment by alsegno** [comment]
As I understand it, each node will have an OAuth provider, and the Davros instance on that node will always use that provider. @mgax can clarify.

**Comment by alsegno** [comment]
@nightsh what's the current status of this? I'd love to close it :)

**Comment by nightsh** [comment]
Hold it there, don't close it yet :)
Planning to resume hacking Davros this evening / tomorrow AM and come back here with an update (final or not). Does it sound reasonable?

**Comment by alsegno** [comment]
Yes :)

**Comment by alsegno** [comment]
How's it going?

**Comment by alsegno** [comment]
Current status:

@nightsh has proven that OAuth authentication works against our OAuth provider.
@nightsh to provide a working system & supplementary information for testing.

Next steps:

@nightsh to work on persistent sessions
@nightsh then to work on dockerizing the application

**Comment by alsegno** [comment]
@alsegno to test what @nightsh provides

**Comment by Luthieneye** [comment]
Per chat with Stefan we don't need features such Public Link sharing and Desktop Sync client.

**Comment by alsegno** [comment]
@nightsh can you give me a link to your repository for the narrative report, and close this if it's time?

**Comment by nightsh** [comment]
Closing it... :wink: 

Here are the links: 
**github:** https://github.com/liquidinvestigations/davros/tree/feature/oauth-middleware
**main readme new section:** https://github.com/liquidinvestigations/davros/tree/feature/oauth-middleware#oauth
**auth specific readme:** https://github.com/liquidinvestigations/davros/blob/feature/oauth-middleware/docs/authentication.md
