### ISSUE TITLE
Hoover - acquire data via Davros

### ISSUE THREAD

**Issue by Luthieneye** [liquidinvestigations/liquidinvestigations#8]
Import Data collections in Hoover via Davros (allow users to upload their own data without the help of a sys admin); 

Data collections to sync with Davros (for file-sharing).

(Feature prioritization here:
http://sentre.de:6080/grain/cMhWLtbhRMZQnscXFpBG92)

**Comment by Luthieneye** [comment]
How does that exactly work? Will Hoover ingest a big fat collection from Davros? or will it be on a folder basis ?

**Comment by mgax** [comment]
Davros will be the only way to import collections. Perhaps each top-level folder in davros will become a Hoover collection. If we do things right, after you import a collection into hoover, you can add more files to it with Davros, and Hoover will pick up the new files.

**Comment by alsegno** [comment]
I don't think we want each top level folder to be a hoover collection, maybe we want a /hoover/ folder at the top level so that davros is still usable for casual filesharing?

**Comment by alsegno** [comment]
This is to be delivered mid-September by @mgax

**Comment by alsegno** [comment]
@mgax Please help me understand what you plan to deliver for mid-September -- does this include any modifications to Davros (dockerization, authorization, &c.?), or is this only liquid system stuff?

**Comment by mgax** [comment]
For this issue, I'll add hoover support for indexing a collection from the filesystem. The process is currently manual and involved; it needs to be automated. And we don't have to index all top-level collections - there could be a page, in hoover or liquid-core, with a list of top-level folders, and a button for each folder, "make a hoover collection".

There is still remaining work for davros dockerization (e.g. for ARM) and authentication (there is no logout support, and maybe we should use Victor's oauth solution, instead of the hacked-together reverse proxy), but they should be separate issues.

**Comment by alsegno** [comment]
Is #22 covered under this as well?

**Comment by mgax** [comment]
Yes, this ticket depends on #22.

**Comment by gabriel-v** [comment]
closed by all of these:
- https://github.com/hoover/snoop/pull/42
- https://github.com/hoover/search/pull/24
- https://github.com/liquidinvestigations/setup/pull/66

**Comment by gabriel-v** [comment]
all PRs are closed, this is done
